---
engines:
  duplication:
    enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.scss"
  - "**.js"
  - "**.html"
exclude_paths:
- config/
- docs/
- tests/
- vendor/
